server:
  port: 8081
spring:
  application:
    name: CUSTOMER-SERVICE
  cloud.discovery.enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
  h2:
    console:
      enabled: true
#EUREKA_URI: http://localhost:8888/eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


