server:
  port: 8082
spring:
  application:
    name: BILLING-SERVICE
  cloud.discovery.enabled: true
  datasource:
    url: jdbc:h2:mem:billing-db
  h2:
    console:
      enabled: true
#EUREKA_URI: http://localhost:8888/eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
