#server.port: 8888
server.port: 8761
eureka:
  instance.hostname: localhost
  server:
    renewal-percent-threshold: 0.50
  client:
    #Dont register yourself as a client
    fetch-registry: false
    #Dont register yourself in the client registry
    register-with-eureka: false
